/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumbs: typeof import('./components/ui/Breadcrumbs.vue')['default']
    EmailIcon: typeof import('./components/iconsax/EmailIcon.vue')['default']
    LockIcon: typeof import('./components/iconsax/LockIcon.vue')['default']
    Login: typeof import('./components/auth/forms/Login.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    PasswordRecoveryEmailStep: typeof import('./components/auth/forms/PasswordRecoveryEmailStep.vue')['default']
    PasswordRecoveryOtpStep: typeof import('./components/auth/forms/PasswordRecoveryOtpStep.vue')['default']
    ResetPasswordStep: typeof import('./components/auth/forms/ResetPasswordStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/users/forms/UserForm.vue')['default']
    UserFormModal: typeof import('./components/users/modals/UserFormModal.vue')['default']
  }
}
