/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(public)/': RouteRecordInfo<'/(public)/', '/', Record<never, never>, Record<never, never>>,
    '/(public)/forgot-password/': RouteRecordInfo<'/(public)/forgot-password/', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/(public)/forgot-password/check': RouteRecordInfo<'/(public)/forgot-password/check', '/forgot-password/check', Record<never, never>, Record<never, never>>,
    '/(public)/forgot-password/reset-password': RouteRecordInfo<'/(public)/forgot-password/reset-password', '/forgot-password/reset-password', Record<never, never>, Record<never, never>>,
    '/(private)/dashboard/': RouteRecordInfo<'/(private)/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/(private)/dashboard/branches/': RouteRecordInfo<'/(private)/dashboard/branches/', '/dashboard/branches', Record<never, never>, Record<never, never>>,
    '/(private)/dashboard/clients/': RouteRecordInfo<'/(private)/dashboard/clients/', '/dashboard/clients', Record<never, never>, Record<never, never>>,
    '/(private)/dashboard/users/': RouteRecordInfo<'/(private)/dashboard/users/', '/dashboard/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(public)/index.vue': {
      routes: '/(public)/'
      views: never
    }
    'src/pages/(public)/forgot-password/index.vue': {
      routes: '/(public)/forgot-password/'
      views: never
    }
    'src/pages/(public)/forgot-password/check.vue': {
      routes: '/(public)/forgot-password/check'
      views: never
    }
    'src/pages/(public)/forgot-password/reset-password.vue': {
      routes: '/(public)/forgot-password/reset-password'
      views: never
    }
    'src/pages/(private)/dashboard/index.vue': {
      routes: '/(private)/dashboard/'
      views: never
    }
    'src/pages/(private)/dashboard/branches/index.vue': {
      routes: '/(private)/dashboard/branches/'
      views: never
    }
    'src/pages/(private)/dashboard/clients/index.vue': {
      routes: '/(private)/dashboard/clients/'
      views: never
    }
    'src/pages/(private)/dashboard/users/index.vue': {
      routes: '/(private)/dashboard/users/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
